name: Deployment

on: [pull_request]

jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v0
        with:
          token_format: access_token
          credentials_json: ${{ secrets.GCP_SA_KEY_WEP_DEV }}
      - name: Login to GCR
        uses: docker/login-action@v1
        with:
          registry: gcr.io
          username: oauth2accesstoken
          password: ${{ steps.auth.outputs.access_token }}
      - name: Build and push
        uses: docker/build-push-action@v2
        env:
          PROJECT_ID: ${{ secrets.GCP_PROJECT_ID_WEP_DEV }}
        with:
          tags: eu.gcr.io/${PROJECT_ID}/${GITHUB_REPOSITORY}/main:${GITHUB_SHA}
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Create manifest
        env:
          BRANCH_NAME: ${{ github.event.pull_request.head.ref }}
          PROJECT_ID: ${{ secrets.GCP_PROJECT_ID_WEP_DEV }}
        run: |
          node ./config/create-gke-manifest.js
          ls -al ./kubernetesConfigs
      - name: Prepare and authenticate kubectl
        uses: google-github-actions/get-gke-credentials@main
        with:
          cluster_name: funiciello-dev-cluster
          location: europe-west6
          project_id: wepublish-dev
          credentials: ${{ secrets.GCP_SA_KEY_WEP_DEV }}
      - name: Deploy to kubernetes
        run: kubectl apply -f ./kubernetesConfigs
      - name: Slack Notification
        if: success()
        env:
          BRANCH_NAME: ${{ github.event.pull_request.head.ref }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
          PROJECT_ID: ${{ secrets.GCP_PROJECT_ID_WEP_DEV }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_WP_DEV_CHANNEL }}
        run: |
          cd ./config
          yarn install
          node ./notify.js
#  e2eTest:
#    needs: deployment
#    name: Runs e2e Test on Feature instance
#    runs-on: self-hosted
#    container:
#      image: testcafe/testcafe
#      options: --user root
#    env:
#      BRANCH_NAME: ${{ github.event.pull_request.head.ref }}
#    steps:
#      - uses: actions/checkout@v2
#      - name: Sleep for 60s
#        uses: juliangruber/sleep-action@v1
#        with:
#          time: 60s
#      - name: Run E2E tests
#        if: always()
#        run: /opt/testcafe/docker/testcafe-docker.sh chromium:headless tests/e2e.ts --assertion-timeout 10000
